/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulosUsuariosRouteImport } from './routes/modulos.usuarios'
import { Route as ModulosStatusRouteImport } from './routes/modulos.status'
import { Route as ModulosSchedulerRouteImport } from './routes/modulos.scheduler'
import { Route as ModulosProjetosRouteImport } from './routes/modulos.projetos'
import { Route as ModulosPainelRouteImport } from './routes/modulos.painel'
import { Route as ModulosLogsRouteImport } from './routes/modulos.logs'
import { Route as ModulosIntegracoesRouteImport } from './routes/modulos.integracoes'
import { Route as ModulosGruposRouteImport } from './routes/modulos.grupos'
import { Route as ModulosDominiosRouteImport } from './routes/modulos.dominios'
import { Route as ModulosAcessoRouteImport } from './routes/modulos.acesso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosUsuariosRoute = ModulosUsuariosRouteImport.update({
  id: '/modulos/usuarios',
  path: '/modulos/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosStatusRoute = ModulosStatusRouteImport.update({
  id: '/modulos/status',
  path: '/modulos/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosSchedulerRoute = ModulosSchedulerRouteImport.update({
  id: '/modulos/scheduler',
  path: '/modulos/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosProjetosRoute = ModulosProjetosRouteImport.update({
  id: '/modulos/projetos',
  path: '/modulos/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosPainelRoute = ModulosPainelRouteImport.update({
  id: '/modulos/painel',
  path: '/modulos/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosLogsRoute = ModulosLogsRouteImport.update({
  id: '/modulos/logs',
  path: '/modulos/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosIntegracoesRoute = ModulosIntegracoesRouteImport.update({
  id: '/modulos/integracoes',
  path: '/modulos/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosGruposRoute = ModulosGruposRouteImport.update({
  id: '/modulos/grupos',
  path: '/modulos/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosDominiosRoute = ModulosDominiosRouteImport.update({
  id: '/modulos/dominios',
  path: '/modulos/dominios',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosAcessoRoute = ModulosAcessoRouteImport.update({
  id: '/modulos/acesso',
  path: '/modulos/acesso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulos/acesso': typeof ModulosAcessoRoute
  '/modulos/dominios': typeof ModulosDominiosRoute
  '/modulos/grupos': typeof ModulosGruposRoute
  '/modulos/integracoes': typeof ModulosIntegracoesRoute
  '/modulos/logs': typeof ModulosLogsRoute
  '/modulos/painel': typeof ModulosPainelRoute
  '/modulos/projetos': typeof ModulosProjetosRoute
  '/modulos/scheduler': typeof ModulosSchedulerRoute
  '/modulos/status': typeof ModulosStatusRoute
  '/modulos/usuarios': typeof ModulosUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulos/acesso': typeof ModulosAcessoRoute
  '/modulos/dominios': typeof ModulosDominiosRoute
  '/modulos/grupos': typeof ModulosGruposRoute
  '/modulos/integracoes': typeof ModulosIntegracoesRoute
  '/modulos/logs': typeof ModulosLogsRoute
  '/modulos/painel': typeof ModulosPainelRoute
  '/modulos/projetos': typeof ModulosProjetosRoute
  '/modulos/scheduler': typeof ModulosSchedulerRoute
  '/modulos/status': typeof ModulosStatusRoute
  '/modulos/usuarios': typeof ModulosUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulos/acesso': typeof ModulosAcessoRoute
  '/modulos/dominios': typeof ModulosDominiosRoute
  '/modulos/grupos': typeof ModulosGruposRoute
  '/modulos/integracoes': typeof ModulosIntegracoesRoute
  '/modulos/logs': typeof ModulosLogsRoute
  '/modulos/painel': typeof ModulosPainelRoute
  '/modulos/projetos': typeof ModulosProjetosRoute
  '/modulos/scheduler': typeof ModulosSchedulerRoute
  '/modulos/status': typeof ModulosStatusRoute
  '/modulos/usuarios': typeof ModulosUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modulos/acesso'
    | '/modulos/dominios'
    | '/modulos/grupos'
    | '/modulos/integracoes'
    | '/modulos/logs'
    | '/modulos/painel'
    | '/modulos/projetos'
    | '/modulos/scheduler'
    | '/modulos/status'
    | '/modulos/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modulos/acesso'
    | '/modulos/dominios'
    | '/modulos/grupos'
    | '/modulos/integracoes'
    | '/modulos/logs'
    | '/modulos/painel'
    | '/modulos/projetos'
    | '/modulos/scheduler'
    | '/modulos/status'
    | '/modulos/usuarios'
  id:
    | '__root__'
    | '/'
    | '/modulos/acesso'
    | '/modulos/dominios'
    | '/modulos/grupos'
    | '/modulos/integracoes'
    | '/modulos/logs'
    | '/modulos/painel'
    | '/modulos/projetos'
    | '/modulos/scheduler'
    | '/modulos/status'
    | '/modulos/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulosAcessoRoute: typeof ModulosAcessoRoute
  ModulosDominiosRoute: typeof ModulosDominiosRoute
  ModulosGruposRoute: typeof ModulosGruposRoute
  ModulosIntegracoesRoute: typeof ModulosIntegracoesRoute
  ModulosLogsRoute: typeof ModulosLogsRoute
  ModulosPainelRoute: typeof ModulosPainelRoute
  ModulosProjetosRoute: typeof ModulosProjetosRoute
  ModulosSchedulerRoute: typeof ModulosSchedulerRoute
  ModulosStatusRoute: typeof ModulosStatusRoute
  ModulosUsuariosRoute: typeof ModulosUsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/usuarios': {
      id: '/modulos/usuarios'
      path: '/modulos/usuarios'
      fullPath: '/modulos/usuarios'
      preLoaderRoute: typeof ModulosUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/status': {
      id: '/modulos/status'
      path: '/modulos/status'
      fullPath: '/modulos/status'
      preLoaderRoute: typeof ModulosStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/scheduler': {
      id: '/modulos/scheduler'
      path: '/modulos/scheduler'
      fullPath: '/modulos/scheduler'
      preLoaderRoute: typeof ModulosSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/projetos': {
      id: '/modulos/projetos'
      path: '/modulos/projetos'
      fullPath: '/modulos/projetos'
      preLoaderRoute: typeof ModulosProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/painel': {
      id: '/modulos/painel'
      path: '/modulos/painel'
      fullPath: '/modulos/painel'
      preLoaderRoute: typeof ModulosPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/logs': {
      id: '/modulos/logs'
      path: '/modulos/logs'
      fullPath: '/modulos/logs'
      preLoaderRoute: typeof ModulosLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/integracoes': {
      id: '/modulos/integracoes'
      path: '/modulos/integracoes'
      fullPath: '/modulos/integracoes'
      preLoaderRoute: typeof ModulosIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/grupos': {
      id: '/modulos/grupos'
      path: '/modulos/grupos'
      fullPath: '/modulos/grupos'
      preLoaderRoute: typeof ModulosGruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/dominios': {
      id: '/modulos/dominios'
      path: '/modulos/dominios'
      fullPath: '/modulos/dominios'
      preLoaderRoute: typeof ModulosDominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/acesso': {
      id: '/modulos/acesso'
      path: '/modulos/acesso'
      fullPath: '/modulos/acesso'
      preLoaderRoute: typeof ModulosAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulosAcessoRoute: ModulosAcessoRoute,
  ModulosDominiosRoute: ModulosDominiosRoute,
  ModulosGruposRoute: ModulosGruposRoute,
  ModulosIntegracoesRoute: ModulosIntegracoesRoute,
  ModulosLogsRoute: ModulosLogsRoute,
  ModulosPainelRoute: ModulosPainelRoute,
  ModulosProjetosRoute: ModulosProjetosRoute,
  ModulosSchedulerRoute: ModulosSchedulerRoute,
  ModulosStatusRoute: ModulosStatusRoute,
  ModulosUsuariosRoute: ModulosUsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
